// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/statlynk-site/About.tsx": () => import("../components/mockups/statlynk-site/About.tsx"),
  "./components/mockups/statlynk-site/CaseStudies.tsx": () => import("../components/mockups/statlynk-site/CaseStudies.tsx"),
  "./components/mockups/statlynk-site/Contact.tsx": () => import("../components/mockups/statlynk-site/Contact.tsx"),
  "./components/mockups/statlynk-site/Home.tsx": () => import("../components/mockups/statlynk-site/Home.tsx"),
  "./components/mockups/statlynk-site/Industries.tsx": () => import("../components/mockups/statlynk-site/Industries.tsx"),
  "./components/mockups/statlynk-site/Insights.tsx": () => import("../components/mockups/statlynk-site/Insights.tsx"),
  "./components/mockups/statlynk-site/Services.tsx": () => import("../components/mockups/statlynk-site/Services.tsx")
};
